### ISSUE TITLE
Mr. Pozm

### ISSUE THREAD

**Issue by NotDSF** [psuDevelopment/api-wrappers#1]
![firefox_JNSTs8LFcN](https://user-images.githubusercontent.com/67711164/107884804-cb7a6500-6eee-11eb-99ba-c3f00d645e13.png)

**Comment by NotDSF** [comment]
His name is Bruno Diferente

**Comment by char-ptr** [comment]
thank you for this informative information i will make sure to copy this down.

**Comment by cateVM** [comment]
yes

**Comment by Perthys** [comment]
shut the fuck up  you fucking black boys

**Comment by Perthys** [comment]
CRINGE monke
